# deployment/cloud_run/service-prod.yaml
# Production Cloud Run service configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wattsmybill-app
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: 'true'
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '50'
    spec:
      containerConcurrency: 100
      timeoutSeconds: 3600
      serviceAccountName: wattsmybill-run-prod@wattsmybill-prod.iam.gserviceaccount.com
      containers:
      - image: australia-southeast1-docker.pkg.dev/wattsmybill-prod/wattsmybill/wattsmybill-app:latest
        ports:
        - name: http1
          containerPort: 8501
        env:
        - name: ENVIRONMENT
          value: production
        - name: DEBUG
          value: 'false'
        - name: GOOGLE_CLOUD_PROJECT
          value: wattsmybill-prod
        resources:
          limits:
            cpu: '4'
            memory: 4Gi
          requests:
            cpu: '2'
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10